-- no-transaction
--
-- Safety net for migration 011. A CREATE INDEX CONCURRENTLY that fails partway
-- (e.g. is cancelled) leaves the index behind in an invalid state, and 011's
-- `IF NOT EXISTS` then silently reuses it on retry -- the index "exists" but
-- is unusable, so the flush worker's expiry sweep silently falls back to a
-- sequential scan.
--
-- REINDEX INDEX CONCURRENTLY is the documented recovery path for such an
-- invalid index: it rebuilds it online (no lock that blocks reads/writes on
-- the table) and works regardless of row count, so it does not assume the
-- outbox table is empty. It is idempotent -- reindexing an already-valid index
-- is a no-op that ends in the same state.
--
-- This must be a single statement: sqlx runs a `-- no-transaction` migration
-- as one simple-protocol query, and REINDEX CONCURRENTLY cannot run inside a
-- transaction block or a DO block, so it has to be the whole file on its own.
REINDEX INDEX CONCURRENTLY access_token_revocation_outbox_expires_at_idx;
